@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package dev.xkmc.golemdungeons.compat.jerotes_village_golems;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;